### ISSUE TITLE
DIP issue

### ISSUE THREAD

**Issue by Ayesha34** [cornell-dti/office-hours#113]
If possible there is a long list of initial parameters that makes reading the code difficult. If possible break it up into separate parts or add comments to make distinctive parts.

**Comment by Ayesha34** [comment]
https://github.com/cornell-dti/office-hours/blob/master/client/src/components/pages/ProfessorPeopleView.tsx

**Comment by SamChou19815** [comment]
Parameter list is much shorter now.
