### ISSUE TITLE
OCP Violation [DevSesh 11]

### ISSUE THREAD

**Issue by JBoss925** [cornell-dti/office-hours#116]
[For DevSesh 11]

handleRemoveChildTag in [ProfessorTagInfo.tsx](https://github.com/cornell-dti/office-hours/blob/master/client/src/components/includes/ProfessorTagInfo.tsx) breaks the Open Closed Principle. It relies extremely heavily on a lot of objects (which makes it open to modification instead of closed) and it doesn't seem like it's done yet (corner cases implemented).

Also, I'm confused as to why creating and editing assignments is in the ProfessorTagInfo class.

**Comment by SamChou19815** [comment]
Close since the link is broken.
