### ISSUE TITLE
Google user profile images don't load.

### ISSUE THREAD

**Issue by rockon999** [cornell-dti/office-hours#119]
The user profile image in the the upper right hand dropdown is not loading correctly.

Browser: Chrome v71
OS: Linux

![profile](https://user-images.githubusercontent.com/2943271/53146749-65fb7400-3573-11e9-9064-00129ec8a2fb.png)

This bug also occured in the announcement screenshot for 3110 on Discourse.

**Comment by Glitched** [comment]
I'm still unable to reproduce. Is there a chance that you have updated your profile pic since logging into QMI? I'm not sure if we handle this case

**Comment by rockon999** [comment]
@Glitched I realized Google will always default to my Cornell account when signing into your site (which isn't my default Google account typically). I have no profile photo set on my Cornell account, so I would guess you aren't providing a default image/handling that case.
