### ISSUE TITLE
courseId defaults to 2 for new users

### ISSUE THREAD

**Issue by BobbyVillaluz** [cornell-dti/office-hours#138]
When users are new to QMI, they default to an inactive courseId of 2 which is in App.tsx. We have to manually update this data right now, but when we switch to our course enrollment model, this value should be queried from the user's personal list of courses. 

"<Redirect from="/" to={'/course/' + (String(window.localStorage.getItem('lastid') || 2))} />"

**Comment by SamChou19815** [comment]
Now we have a much better routing system that accounts for enrollment model.
