### ISSUE TITLE
Editing office hours session should have values pre-populated

### ISSUE THREAD

**Issue by ngwattcos** [cornell-dti/office-hours#337]
As in title.

![image](https://user-images.githubusercontent.com/18223523/79521207-967b5880-8026-11ea-94db-0daa521905f1.png)

**Comment by vanessaw1** [comment]
Is this for an existing office hour session? Unsure how to reproduce this issue
![image](https://user-images.githubusercontent.com/9014225/79697474-aa060980-8248-11ea-94cc-72ab13cacf3a.png)

**Comment by ngwattcos** [comment]
This might be an inconsistent bug. When I was editing a session during today's meeting, I noticed that the values were pre-populated.
