### ISSUE TITLE
Unable to Save Edits to Office Hours Series Times...

### ISSUE THREAD

**Issue by ngwattcos** [cornell-dti/office-hours#380]
... when "Edit all office hours in this series" is checked.

<img width="1135" alt="Screen Shot 2020-09-10 at 4 10 39 PM" src="https://user-images.githubusercontent.com/18223523/92797817-68edcd80-f380-11ea-8a44-ef09a7e14008.png">
<img width="1166" alt="Screen Shot 2020-09-10 at 4 10 43 PM" src="https://user-images.githubusercontent.com/18223523/92797819-68edcd80-f380-11ea-8370-375923f265f7.png">

The hours do not update.

**Comment by ewlsh** [comment]
This isn't a series, so maybe that is part of the problem?
