### ISSUE TITLE
Edit Office Hours Menu Opens After Closing

### ISSUE THREAD

**Issue by ngwattcos** [cornell-dti/office-hours#381]
How to replicate:
1. Go to "Manage Hours" tab in the Professor View.
2. click "Edit" button on an office hours session
3. Change either the start or end time. (changing start time usually changes end time). _**Deselect "Edit all office hours in this series"**_.

The menu box should close and then open again.

**Comment by ewlsh** [comment]
Yes I can reproduce this annoying bug, for me just clicking submit again fixes it.

**Comment by ewlsh** [comment]
Addressed in #393
