### ISSUE TITLE
Top bar does not handle courses that have ended correctly

### ISSUE THREAD

**Issue by abcdefguan** [cornell-dti/office-hours#448]
You can see from this image that the top bar lets users choose between {CS 3110, Test, Info 4998}
![Screenshot from 2020-12-16 09-13-17](https://user-images.githubusercontent.com/9957585/102359619-04459e80-3f7f-11eb-8435-898422ad08e8.png)
However, if you look at edit courses, only Test and Info 4998 appear
![Screenshot from 2020-12-16 09-14-02](https://user-images.githubusercontent.com/9957585/102359652-0f003380-3f7f-11eb-9ed8-340a28464e20.png)
It turns out that CS 3110 expired on 18 Oct and should no longer be selectable
![Screenshot from 2020-12-16 09-14-54](https://user-images.githubusercontent.com/9957585/102359748-2e975c00-3f7f-11eb-8c32-9df19cae3813.png)
When clicking on CS 3110 from the top bar options, nothing happens and you don't actually go to CS 3110's office hours.

Current Behaviour: Expired courses (CS 3110) appear on top bar and are selectable but selection results in no progression.
Correct Behaviour: Expired courses (CS 3110) should not appear on top bar

**Comment by ngwattcos** [comment]
@abcdefguan Have not confirmed but I suspect that the start date of January 20 is the real reason it is not showing up.

**Comment by abcdefguan** [comment]
Why would that be the case? When do you cut off the start dates (how many months)?
You should consolidate the former classes logic with the logic used to display tabs on the top bar.
