### ISSUE TITLE
App outright fails to load on iPhone / iPad

### ISSUE THREAD

**Issue by abcdefguan** [cornell-dti/office-hours#526]
Reported by a student on iPhone. Reported to be working in Feb, but not working now.
Tested on iPad with iOS 14.4, Chrome and Safari

App displays a blank screen after logging in

**Comment by ngwattcos** [comment]
@pooja654 and I are not able to recreate this bug on iPhone. I remember a TA complaining of this issue a while back. Can we get more information on how the bug occurs?

**Comment by abcdefguan** [comment]
When trying to login, It points me towards that google login link and lets me fill up my details. After that's done, it displays a loading icon for a bit and it gives me a blank screen that's the same color as the loading icon. It failed on 2 separate iPads running iOS 14.1 and 14.4 on both Safari and Chrome on my end.

**Comment by ngwattcos** [comment]
That is quite curious. It is possible that some calls to the notification API have not been caught, although I'm puzzled on why it works on half of iOS devices (I have iOS 14.4, safari). Perhaps it is because I didn't have to log in and the authentication process is bugged.

**Comment by abcdefguan** [comment]
That's odd. Maybe it has to do with the authentication process. (??). See if you could borrow an new iPad / iPhone or clear your cache and cookies and see if the problem appears.
